# Etapa de build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Moto/MotoApi/MotoApi.csproj", "Moto/MotoApi/"]
RUN dotnet restore "Moto/MotoApi/MotoApi.csproj"
COPY . .
WORKDIR "/src/Moto/MotoApi"
RUN dotnet publish "MotoApi.csproj" -c Release -o /app

# Etapa final da API
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app /app
EXPOSE 8080
ENTRYPOINT ["dotnet", "MotoApi.dll"]
