version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: MotosDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  moto-api:
    build: .
    depends_on:
      - kafka
      - postgres
    ports:
      - "5000:80"
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MotosDB;Username=admin;Password=admin123;
    volumes:
      - ./Moto/MotoApi:/app
    working_dir: /app
    command: [
      "/bin/sh", "-c",
      "dotnet restore && dotnet build && dotnet run --project MotoApi.csproj"
    ]

volumes:
  postgres_data: