// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251009233807_UpdateMotoIdentificadorToStringV2")]
    partial class UpdateMotoIdentificadorToStringV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoApi.Models.Moto", b =>
                {
                    b.Property<string>("Identificador")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasAnnotation("Relational:JsonPropertyName", "placa");

                    b.HasKey("Identificador");

                    b.HasIndex(new[] { "Placa" }, "IX_Motos_Placa")
                        .IsUnique();

                    b.ToTable("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
